const String server1_api_url = "http://172.20.10.2:8000/";

const String server2_api_url = "http://172.20.10.2:8080/";

const List<String> brandNames = [
  'American Bull',
  'Camla',
  'Cross Court',
  'ElaBaroda',
  'Hypernation',
  'The Indian Garage',
  'A okay',
  'AD by Aravimdh',
  'ANFOLD',
  'Aazing London',
  'Aesthetic Bodies',
  'Allen Solly',
  'Allen Solly Tribe',
  'American Eagle',
  'American Swan',
  'Amrut Varsha Creation',
  'Andamen',
  'Antony Morato',
  'Anuok',
  'Armisto',
  'Arrow Newyork',
  'Arrow Sport',
  'Balista',
  'Basics',
  'Bawerin',
  'Beat London',
  'Bedgasm',
  'Being Human',
  'Bene Kleed',
  'Bewakoof',
  'BigBanana',
  'Black Berry',
  'Black Coffe',
  'Blamblack',
  'Bossini',
  'Braclo',
  'Break Bounce',
  'British club',
  'Brunn & Stengade',
  'Bushirt',
  'Byford By Pantaloons',
  'Callno Lodon',
  'Calvin Klein Jeans',
  'Campus Sutra',
  'Canary Lodon',
  'Canoe',
  'Cantabil',
  'Cape Canary',
  'Cavallo By LInen',
  'Celio',
  'Chennis',
  'Cherokke',
  'Chkokko',
  'Classic Polo ',
  'Club York',
  'Cobb',
  'Code By Lifestyle',
  'Color Plus',
  'Colt',
  'Columbia',
  'Colvynharris',
  'Copperline',
  'Crimsoune Cloub',
  'Crocodile',
  'Croydon',
  'Croydon Uk',
  'D Kumar',
  'Dcot By Donear',
  'Dejano',
  'Denimize by Fame Forever',
  'Dennis Lingo',
  'Dennison',
  'Dillinger',
  'Disrupt',
  'Don Vino',
  'Donzell',
  'Double Two',
  'Drean of Glory INC ',
  'Ducati',
  'Ecentric',
  'Emerals',
  'Encore By Invictus',
  'English Navy',
  'Eppe ',
  'Estela',
  'Ether',
  'Ethnix By Raymond',
  'Even',
  'Evooq',
  'Fabindia',
  'Fame Forever By Lifestyle',
  'Fashion Fricks',
  'Finnoy',
  'Firangi Yarn',
  'Flying Machine',
  'Foga',
  'Forca',
  'Forca By Lifestyle',
  'Forcaz By Decathlon',
  'Forever ',
  'Four One Oh',
  'FreeSoul',
  'French Connection',
  'French Crown',
  'Fubar',
  'Fugazze',
  'Gant',
  'Gespo',
  'Globus',
  'Glordano',
  'Green Fibre',
  'GreenFibre',
  'Gristones',
  'HERE & NOW',
  'Hancock',
  'Hangup',
  'Harsam',
  'Harvard',
  'Hatheli ',
  'High Star',
  'Highlander',
  'HubberHolme',
  'Huetrap',
  'Huggun',
  'INVICTUS',
  'IVOC',
  'Identiti',
  'Imyoung',
  'Indian Terrian',
  'Indo Era',
  'Indus Route By Pantaloons',
  'JANISH',
  'LOCOMOTIVE',
  'Levis',
  'Mast & Harbour',
  'Nautica',
  'Nirvaan',
  'Park Avenue',
  'Parx',
  'Peter England',
  'R&B',
  'Raymond',
  'Roadster',
  'SELECTED',
  'Shaftesbury London',
  'Sojanya',
  'Soratia',
  'Sztori',
  'The Bear House',
  'Tisbtane',
  'Tommy Hilfiger',
  'US POLO',
  'United Colors of Benetto',
  'V Mart',
  'Van Heusen Denim Labs',
  'Van Heusen Sport',
  'WROGN',
  'Wild West',
  'abof',
  'excalibur'
];
